apiVersion: v1
kind: Service
metadata:
  labels: 
    run: tomcat 
  name: tomcat 
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 4001
    port: 80
    targetPort: 1000
    protocol: TCP
  selector:
    run: tomanitesh
    type: NodePort
status:
  loadBalancer: {}
