apiVersion: v1
kind: Service
metadata:
  name: tomanitesh
  labels:
    run: tomanitesh
spec:
  ports:
  - nodePort: 3000
    port: 80
    targetPort: 1000
    protocol: TCP
  selector:
    run: tomanitesh
#status:
#loadBalancer: {}
