apiVersion: v1
kind: Service
metadata:
  labels: 
    run: tomcat 
  name: tomcat 
  namespace: default
spec:
  clusterIP: 10.245.100.130 
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 3000
    port: 80
    targetPort: 1000
    protocol: TCP
  selector:
    run: tomanitesh
    type: NodePort
#status:
#loadBalancer: {}
